version: "3"

dotenv:
  - project.env

tasks:
  source:
    cmds:
      - mvn dependency:sources
  update:
    cmds:
      - "mvn versions:set -DnewVersion=${PROJECT_VERSION}"
      - mvn versions:commit
      - echo "set to new version ${PROJECT_VERSION} successfully"
  install:
    cmds:
      - mvn clean install -DskipTests
  package:
    cmds:
      - mvn clean package -DskipTests
